name: testback deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: testback build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: github actions
        run: echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
